name: hardware/mailserver
description: Simple and full-featured mail server using Docker
version: 1.1.0
category: Applications
maintainer: "Hardware <contact@meshup.net>"
license: MIT
projectURL: https://github.com/hardware/mailserver-rancher
